apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-cluster-1
  region: us-east-1

managedNodeGroups:
  - name: expense
    instanceType: m5.large
    desiredCapacity: 03
    spot: true